# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 176005a7e3f2375222d0e7df7a7be5883bffb125c14f4484013238428c25273dcf8bf4c158c0da8424b8356562ed3363377903f84b6bdd1767fce6c6208d91c8

test:
  secret_key_base: 250a8e3756fc417fa7f5a88c436b203e3daeefc1b63f4cf83a3eae3a6823fcf0cdb17d5d30a8c8d706d7621fb9c227c12318b8d3c9dc52612703089ffc10534e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
